### ISSUE TITLE
JavaScript: bad style/scope

### ISSUE THREAD

**Issue by Kronuz** [sublimehq/Packages#1237]
Bad style in nested arrow functions with muti-line arguments:

```javascript
const goodStyle = () => () => {
  // this bock has proper style and scope is returned
  return 'source.js meta.block.js meta.block.js';
};
```

```javascript
const badStyle = () => (
) => {
  // this whole bock has wrong style and scope is returned
  return 'source.js meta.block.js meta.object-literal.js';
};
```

**Comment by Thom1729** [comment]
This is fixed by #1009.

**Comment by Kronuz** [comment]
Nope, unfortunately, is not (only partially). this is still broken:

```javascript
export const badStyle = () => (
) => {
  // this whole bock has wrong style and scope is returned
  return 'source.js meta.block.js meta.object-literal.js';
};
```

**Comment by Thom1729** [comment]
Those two examples are impossible to handle perfectly because Sublime's parser doesn't look past line boundaries, so it's impossible to tell whether `const badStyle = () => (` is opening an argument list or a parenthesized expression. In this case, the best guess is a parenthesized expression.

However, it should be possible to "recover" from a wrong guess when it sees the `=>`. This would provide better results (though still incorrect).

In addition, the expression `(foo,)` probably should not mark the closing paren as invalid. It *is* invalid, but marking it invalid is a bad guess that's likely to screw up the rest of the file. Myself, I would also like to mark the comma in that expression as an operator rather than as punctuation, to distinguish it from the more common use of the comma as true punctuation; this opinion is not widely accepted.

**Comment by wbond** [comment]
I just tested with the latest JavaScript syntax and we are handling these reasonably well, so I am going to close for now.

If we end up finding a way to allow the lexer to handling multiple lines, then we can work on making the syntax handle these correctly.
