### ISSUE TITLE
C++ parser does not handle multi-line function definitions

### ISSUE THREAD

**Issue by DougGore** [sublimehq/Packages#149]
Sublime's C++ syntax highlighter / function name parser does not handle multi-line function definitions.

For example this is handled:
`void MyClass:MyFunction(int32_t param1, int32_t param2)`

But if it's written like this, it does not see it as a function definition any longer:
```
void MyClass:MyFunction
(
  int32_t param1,
  int32_t param2
)
```

There is no green highlighting of the function name and it doesn't appear in the function list when using Ctrl-R.

**Comment by wbond** [comment]
Most likely the syntax will need to be adapted to handle this. We handled a situation like this recently with Go and function definitions that split multiple lines.

The lexer processes one line at a time, and uses regular expressions to determine what it is seeing. We might run into issues with the `(` being on a different line. Somehow we'll need to determine that `type class:function` is incomplete – probably form the fact that there is no closing `;`. However, I could see the following tripping us up:

```c++
int32_t my_func
(int32_t a)
{

}

int32_t my_var
;
```

The reason being that we need to process the first line and assign it scopes before moving on, and we won't know if we have a variable of function until we process the second line.

**Comment by DougGore** [comment]
Could the parser look for the opening { instead? I wasn't clear when raising the issue but I was describing the function body rather than the declaration within the class however both do have the same parsing issue.

**Comment by wbond** [comment]
@DougGore Either way if the symbol that indicates it is a function is on a different line that the name, we are probably going to run into trouble.

We should be able to make it work with:

```C++
int32_t my_func(
    int32_t a)
{

}
```

Since the `(` is on the first line, however as soon as we need to look ahead, I think we are going to run into trouble. However, I will see what I can do.

**Comment by wbond** [comment]
I've been working on the C and C++ syntaxes and am hoping to have handling of this syntax in the next dev build.

**Comment by wbond** [comment]
There is a version of the C/C++ rewrite at https://github.com/sublimehq/Packages/tree/c-rewrite if you want to do some testing. To do so, you should check out the c-rewrite branch and follow the directions at https://github.com/sublimehq/Packages#installation.

Just note that Objective C and Objective C++ are broken right now since I need to rewrite them to work with the new C and C++ syntaxes.

**Comment by wbond** [comment]
This should be fixed in master now

**Comment by DougGore** [comment]
Thanks, I did try to install it a few days ago but it didn't appear to work however I'm not overly familiar with Git, etc. I'll try again when I get a chance and let you know if I'm still seeing the issue. Thanks once again for addressing the issue :-)

**Comment by DougGore** [comment]
Just as a quick follow up I installed the beta version of Sublime 3 and this issue appears fixed. Many thanks wbond for fixing this!
