### ISSUE TITLE
bash/shell syntax highlight broken for indented comments

### ISSUE THREAD

**Issue by keen99** [sublimehq/Packages#1625]
sometime between 3143 and 3170 (and not fixed in 3176, intended comments are no longer recognized.  this leads to significant knock-on effects with things like apostrophes...

two screenshots below, first one is working properly, the second is broken

![3143-shell-ok](https://user-images.githubusercontent.com/1108844/40747889-b200a988-642c-11e8-833c-d2fb24e756e1.png)
![3176-shell-broke](https://user-images.githubusercontent.com/1108844/40747892-b44fc9d0-642c-11e8-88ca-da42e85a4b89.png)

**Comment by rwols** [comment]
See: https://github.com/sublimehq/Packages/issues/1603

**Comment by keen99** [comment]
thats a workaround not a fix

and it resets to the broken at every file save.   so its very very temporary.


--

**Comment by keen99** [comment]
ah #1604 has a suggested fix.

there is a related problem where `Shell-Unix-Generic` is selected at every file save (ignoring attempts to override it to `Bourne Again Shell (bash)` via the menu option)    similarly, something seemed to be breaking the keyboard shortcut for make/remove comments in shell (apple / in my world, dont recall if that was a stock shortcut or not), either fully or intermittently, not sure.

I've switched back to 3143 because sublime became entirely unusable with 3176...

**Comment by rwols** [comment]
> thats a workaround not a fix
> ah #1604 has a suggested fix.

Indeed, the fix is #1604.

> and it resets to the broken at every file save. so its very very temporary.

Default behaviour of Sublime should 1) select the bash syntax by default and 2) not change syntax on every save.

**Comment by rwols** [comment]
This is fixed by https://github.com/sublimehq/Packages/pull/1604.

**Comment by keen99** [comment]
since I am building a new machine, I ran into this again - turns out, `3176` is still the latest build of sublime - and so shell syntax highlighting is still broken.

when is the next release build?  I hate having to run dev builds (which I haven't tried)

**Comment by wbond** [comment]
This seems to be fixed on build 3211 (3.2.2), closing.
