### ISSUE TITLE
[Go] float constant expressed with final dot is not properly marked

### ISSUE THREAD

**Issue by kortschak** [sublimehq/Packages#1852]
The Go spec allows float constant literals to be expressed with a final dot. This is not correctly marked with the current syntax definition.

Using the following code:
```
package main

var a = 1.

func main() {}
```
We see that the syntax highlighting is incorrect compared to the expected below.

![screenshot from 2019-01-27 14-09-02](https://user-images.githubusercontent.com/275221/51796139-1f00b400-223d-11e9-90f7-2f2e84541db1.png)

And the contexts do not include `constant.numeric.float.go`, _cf_ below.
```
source.go
invalid.deprecated.go
```

Expected highlighting,

![screenshot from 2019-01-27 14-08-20](https://user-images.githubusercontent.com/275221/51796127-098b8a00-223d-11e9-86a5-94e740ddf7ca.png)

and contexts.
```
source.go
constant.numeric.float.go
```

/cc @mitranim

**Comment by FichteFoll** [comment]
(This sounds to me like a job for a linter, honestly, but I suppose adding some random meta scope doesn't hurt.)

**Comment by mitranim** [comment]
Well, thinking about it more, I'd want not to mark it invalid, since I never accidentally use this form, but just to make it stand out, easier to visually parse. (Elision makes parsing harder for me.) The `invalid` scoping was definitely a dumb idea.

**Comment by kortschak** [comment]
@mitranim Any update on this?

**Comment by deathaxe** [comment]
@wbond This is fixed by 10c4b5c6051091132083f69518f273acb510835c

**Comment by wbond** [comment]
Thanks @deathaxe!

**Comment by kortschak** [comment]
@wbond Has this been released? The reported behavior is still present as of 3.2.2 build 3211.

**Comment by michaelblyons** [comment]
It's not on the release channel. Dev builds have it, or you can [follow the instructions](https://github.com/sublimehq/Packages#installation) to use it for a particular ST installation.

**Comment by kortschak** [comment]
Thanks

**Comment by kortschak** [comment]
Are these going to be back-ported to mainline?

**Comment by wbond** [comment]
These will be part of the next stable release, yes, as the dev builds build up to a stable release.

**Comment by kortschak** [comment]
Thanks
