### ISSUE TITLE
[Scala] New Changes Break MarkdownEditing Package

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#573]
This breakage predates my latest flurry of PRs.  I'm not sure exactly what's happening, but the MarkdownEditing package is now exhibiting invalid regular expressions when embedding Scala code in markdown using triple backticks.

The exact error:

> too short multibyte code string in regex \\b(def)\\s+((?:(?:[$_\\p{Lu}](?:(?:[$\\p{Lu}\\p{Ll}\\p{Lt}\\p{Lo}\\p{Nl}0-9]|\_(?=[^[\\p{Sm}\\p{So}[[^\\w\[\\]\(\\)\{\\}'";,.\`\_\\s]&&[\\x20-\\x7F]]]]))\*(?:\_(?x:
  [[^:=<@←⇒#]&&[\\p{Sm}\\p{So}[[^\\w\[\\]\(\\)\{\\}'";,.\`\_\\s]&&[\\x20-\\x7

The next character should be `F`.  Not sure why it would truncate early.

**Edit** It looks like MarkdownEditing handles fenced Scala blocks by including `source.scala`.  Thusly: https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown.tmLanguage#L1884  I'm assuming this problem is arising due to the Scala mode being `sublime-syntax` and MarkdownEditing being `tmLanguage`?

**Comment by wbond** [comment]
No, there are no problems with interfacing between `.tmLanguage` and `.sublime-syntax` files, to my knowledge. All `.tmLanguage` files are interpreted into the same internal data structures as `.sublime-syntax`, so there is no distinction.

It looks like there are raw unicode characters in the variables in `Scala.sublime-syntax`. This is not a good idea, because certain patterns cause lexing to fall back to the Oniguruma regex engine, and it has different rules for byte sequences. I'll replace the raw UTF-8 byte strings with unicode escapes.

**Comment by djspiewak** [comment]
@wbond Should update [the documentation](https://www.sublimetext.com/docs/3/syntax.html) then:

> Note that while Sublime Text supports both .sublime-syntax and .tmLanguage files, it's not possible to include a .tmLanguage file within a .sublime-syntax one.

We definitely shouldn't have raw unicode characters.  I'm surprised that we do, actually, especially since the compatibility checker passes the syntax definitions.

**Comment by wbond** [comment]
The compatibility checker only checks compatibility with the new engine. In this case, the issue was Oniguruma.

Yes, I can update the documentation. Originally that was true, but [changes were made in build 3087 and 3090](https://www.sublimetext.com/3dev).

**Comment by wbond** [comment]
This should be resolved by 8e0c2b4b9016460266448b077ff181359b9a5f04

**Comment by djspiewak** [comment]
Still appears to be a problem, though it gets further in the regex now.

**Comment by wbond** [comment]
I just installed MarkdownEditing and opened a markdown file, but I didn't get any errors. I also added a scala fenced code block.

Can you provide steps to reproduce?

**Comment by djspiewak** [comment]
@wbond Reproduces for me with the following steps:

1. Restart sublime
2. Create a new file with "Markdown GFM" syntax
3. Enter the text \`\`\`scala

Once the second `a` is typed, the following error will appear:

```
too short multibyte code string in regex \b(def)\s+((?:(?:[$\p{Lu}](?:(?:[$\p{Lu}\p{Ll}\p{Lt}\p{Lo}\p{Nl}0-9]|_(?=[^[\p{Sm}\p{So}[[^\w\[\]\(\)\{\}'";,.`_\s]&&[\x20-\x7F]]]]))*(?:_[\p{Sm}\p{So}[[^\w\[\]\(\)\{\}'";,.`_\s]&&[\x20-\x7F]]]+)?)|(?:(?:\p{Ll}|_+(
```

**Comment by wbond** [comment]
Ah, the GFM variant.

**Comment by wbond** [comment]
So I the issue is what I had thought, but my guess as to which element was causing it was wrong.

Oniguruma doesn't like the `\x20-\x7F` range at https://github.com/sublimehq/Packages/blob/master/Scala/Scala.sublime-syntax#L14.

Without `{` and `}`, the `\x` is supposed to denote bytes. This should be fine as those bytes are valid UTF-8. Either way, changing it to use the code point hex escape `\x{20}-\x{7F}` fixes the issue.

**Comment by djspiewak** [comment]
Ah that makes sense.  Part of me had wondered why those particular escapes were inconsistent with the others, but it didn't rise to the conscious surface enough to register.

**Comment by wbond** [comment]
fdd6cd650c9994d86390d615b18143cf19c81682 should truly resolve the issue.

**Comment by djspiewak** [comment]
Confirmed
