### ISSUE TITLE
[JavaScript] arrow function highlighter issue

### ISSUE THREAD

**Issue by stevenvachon** [sublimehq/Packages#741]
```js
function1(arg => {
	return function2('<element attr="value">');
});
```
correctly produces:
![correct](https://cloud.githubusercontent.com/assets/170197/21287638/2a97a1d4-c43e-11e6-8631-3398861afbc2.png)

---

```js
function1(arg => 
{
	return function2('<element attr="value">');
});
```
incorrectly produces:
![incorrect](https://cloud.githubusercontent.com/assets/170197/21287640/382c55d8-c43e-11e6-907f-2c404febc8af.png)

**Comment by wbond** [comment]
This is fixed by 3d1ae166538dcfa994482fede2a35874dccf258e, which will be part of the next dev build

**Comment by stevenvachon** [comment]
@wbond I updated my JavaScript.sublime-package to contain these changes and the issue is not resolved (?)

**Comment by wbond** [comment]
I wouldn't recommend trying to update your JavaScript.sublime-package file directly.

I would follow the directions in the readme of this repo to create an "override".

I just double checked with the latest version of the JavaScript syntax and the sample you have is correctly highlighting.

**Comment by stevenvachon** [comment]
Ok, thank you.
